apiVersion: v1
kind: Service
metadata:
  name: mosquitto-tcp
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-tls
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
    - port: 8883
      targetPort: 8883
      protocol: TCP
